apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-sync
  template:
    metadata:
      labels:
        app: git-sync
    spec:
      containers:
      - name: git-sync
        image: k8s.gcr.io/git-sync/git-sync:v3.1.0
        env:
        - name: GIT_SYNC_REPO
          value: "https://github.com/dohabenhabbach/gitsync.git"
        - name: GIT_SYNC_BRANCH
          value: "main"
        - name: GIT_SYNC_USERNAME
          value: "dohabenhabbach"
        - name: GIT_SYNC_PASSWORD
          value: "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"  # Utilisez un token d'accès personnel pour l'authentification GitHub.
        - name: GIT_SYNC_ROOT
          value: "/mnt/git"
        volumeMounts:
        - name: git-sync-volume
          mountPath: /mnt/git
      volumes:
      - name: git-sync-volume
        emptyDir: {}
